### ISSUE TITLE
pip install on python < 3 fails

### ISSUE THREAD

**Issue by arnewiebalck** [jaraco/jaraco.windows#19]
Hi,

It seems that since a few days, sth like

`pip install --ignore-installed --no-binary :all: 'jaraco.windows; python_version < '"'"'3'"'"''`

fails for all versions of pip on CentOS7 with Python 2.7.5 [0]. Is this a known issue?
(I know that Python 2 has passed its EOL :-)

Thanks in advance for any hints!
 Arne

```
[0]
Collecting jaraco.windows
  Using cached https://files.pythonhosted.org/packages/76/84/5e01f823fb6783a8cf3ba4e9cf11c010a40fddf6037a31d78f13cc1e6b4b/jaraco.windows-4.0.zip
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-YN3LJc/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=34.4' wheel 'setuptools_scm>=1.15'
       cwd: None
  Complete output (49 lines):
  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Collecting setuptools>=34.4
    Using cached https://files.pythonhosted.org/packages/ed/7b/bbf89ca71e722b7f9464ebffe4b5ee20a9e5c9a555a56e2d3914bb9119a6/setuptools-44.1.0.zip
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
    WARNING: Generating metadata for package wheel produced metadata for project name unknown. Fix your #egg=wheel fragments.
  Collecting setuptools_scm>=1.15
    Using cached https://files.pythonhosted.org/packages/f2/48/7c0c1812844593c5e3a8603f00d761c34cd4917198784b46b991407cd3e2/setuptools_scm-4.0.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 2:
     command: /usr/bin/python2 /usr/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3d7zfT/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=34.4' wheel 'jaraco.windows; python_version < '"'"'3'"'"''
         cwd: None
    Complete output (31 lines):
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    Collecting setuptools>=34.4
      Using cached https://files.pythonhosted.org/packages/ed/7b/bbf89ca71e722b7f9464ebffe4b5ee20a9e5c9a555a56e2d3914bb9119a6/setuptools-44.1.0.zip
    Collecting wheel
      Using cached https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
      WARNING: Generating metadata for package wheel produced metadata for project name unknown. Fix your #egg=wheel fragments.
    Collecting jaraco.windows
      Using cached https://files.pythonhosted.org/packages/76/84/5e01f823fb6783a8cf3ba4e9cf11c010a40fddf6037a31d78f13cc1e6b4b/jaraco.windows-4.0.zip
    ERROR: Exception:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 345, in run
        resolver.resolve(requirement_set)
      File "/usr/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
        self._resolve_one(requirement_set, req)
      File "/usr/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/usr/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
        self.require_hashes
      File "/usr/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 213, in prepare_linked_requirement
        with self.req_tracker.track(req):
      File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/lib/python2.7/site-packages/pip/_internal/req/req_tracker.py", line 94, in track
        self.add(req)
      File "/usr/lib/python2.7/site-packages/pip/_internal/req/req_tracker.py", line 63, in add
        % (link, fp.read()))
    LookupError: https://files.pythonhosted.org/packages/76/84/5e01f823fb6783a8cf3ba4e9cf11c010a40fddf6037a31d78f13cc1e6b4b/jaraco.windows-4.0.zip#sha256=d136f63bfb7db671e24849a9f3f6582aa5151265ca96d954b3e29d5bae233307 (from https://pypi.org/simple/jaraco-windows/) (requ
ires-python:>=2.7) is already being built: jaraco.windows from https://files.pythonhosted.org/packages/76/84/5e01f823fb6783a8cf3ba4e9cf11c010a40fddf6037a31d78f13cc1e6b4b/jaraco.windows-4.0.zip#sha256=d136f63bfb7db671e24849a9f3f6582aa5151265ca96d954b3e29d5bae233307
    WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by arnewiebalck** [comment]
While this is with 19.2.3,  20.1.1 exhibits the same issue.

**Comment by jaraco** [comment]
Thanks for reporting the issue, and sorry for the delay in response. I'm surprised by the behavior you describe. I wouldn't expect that to be the case with `pip` 9 or later. Let me see if I can replicate the issue.

**Comment by jaraco** [comment]
I created this dockerfile:

```
from centos:7
run curl https://bootstrap.pypa.io/get-pip.py -o - | python - pip==19.2.3
CMD pip install --ignore-installed --no-binary :all: 'jaraco.windows; python_version < '"'"'3'"'"''
```

And ran it, and it runs to completion, ending with:

```
Successfully installed backports.functools-lru-cache-1.6.1 backports.os-0.1.1 configparser-4.0.2 contextlib2-0.6.0.post1 future-0.18.2 importlib-metadata-2.0.0 importlib-resources-3.3.0 jaraco.classes-2.0 jaraco.collections-2.1 jaraco.functools-2.0 jaraco.structures-2.0 jaraco.text-3.2.0 jaraco.ui-2.0.1 jaraco.windows-4.0 more-itertools-5.0.0 path.py-11.5.2 pathlib2-2.3.5 scandir-1.10.0 singledispatch-3.4.0.3 six-1.15.0 typing-3.7.4.3 zipp-1.2.0
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Looking more closely at the changelog, it looked to me like `setuptools_scm` was requiring `jaraco.windows`, which led to problems, but it appears that in [setuptools 4.1.1](https://github.com/pypa/setuptools_scm/blob/0bd9199f5279ab2855b23b3fcf790827f28d5049/CHANGELOG.rst#v411), that dependency was dropped, and that seems to have fixed this issue.

Please report back if you find otherwise.
